version: '3.5'

services:
    webdav:
        build:
            args:
                CONTAINER_NAME: webdav
                CONTAINER_VERSION: 1.0.1
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180311
                WEBDAV_GROUP: webdav
                WEBDAV_READWRITE: disable
#                WEBDAV_USER: ${CFG_MYSQL_USER}
                WEBDAV_USER: webdav
                WEBDAV_USER_PWD: ${CFG_MYSQL_PASSWORD}
                WEBDAV_WHITELIST: 127.0.0.1
            cache_from:
                - alpine:3.6
                - base_container:20180311
            context: .
            dockerfile: Dockerfile
        container_name: webdav
        environment:
#            WEBDAV_USER: ${CFG_MYSQL_USER}
            WEBDAV_USER: webdav
            WEBDAV_USER_PWD: ${CFG_MYSQL_PASSWORD}
            WEBDAV_GROUP: webdav
            WEBDAV_READWRITE: disable
            WEBDAV_WHITELIST: 127.0.0.1
        hostname: webdav
        image: webdav:20180311
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8003:80
#        restart: unless-stopped
        volumes:
            - ./vols/webdav:/webdav
            - ./vols/log:/var/log 
