version: '3.5'

services:
    webdav:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-dev}
                CONTAINER_NAME: webdav
                CONTAINER_VERSION: 1.0.6
                DEBUG_TRACE: 0
                FROM_BASE: base_container:latest
                WEBDAV_GROUP: webdav
                WEBDAV_READWRITE: disable
                WEBDAV_WHITELIST: 127.0.0.1
            cache_from:
                - alpine:3.6
                - base_container:latest
            context: .
            dockerfile: Dockerfile
        container_name: webdav
        environment:
            WEBDAV_USER: ${CFG_USER}
            WEBDAV_PASS: ${CFG_PASS}
            WEBDAV_GROUP: webdav
            WEBDAV_READWRITE: disable
            WEBDAV_WHITELIST: 127.0.0.1
        hostname: webdav
        image: webdav:latest
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8003:80
#        restart: unless-stopped
        volumes:
            - ./vols/webdav:/webdav
            - ./vols/log:/var/log 
