version: '3.3'

services:
    webdav:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: webdav
                FROM_BASE: ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
                WEBDAV_GROUP: webdav
                WEBDAV_READWRITE: disable
                WEBDAV_WHITELIST: 127.0.0.1
            cache_from:
                - ${DOCKER_REGISTRY:-}${OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${OS:-}base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: webdav
        container_name: webdav
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            WEBDAV_USER: $CFG_USER
            WEBDAV_PASS_FILE: /run/secrets/webdav.pwd
            WEBDAV_GROUP: webdav
            WEBDAV_READWRITE: disable
            WEBDAV_WHITELIST: 127.0.0.1
        hostname: webdav
        image: ${DOCKER_REGISTRY:-}${OS:-}webdav:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8003:80
#        restart: unless-stopped
        secrets:
            - webdav.pwd
        volumes:
            - ./vols/webdav:/webdav
            - ./vols/log:/var/log

secrets:
   webdav.pwd:
     file: ~/.inf/secrets/webdav.password
